### ISSUE TITLE
Wireshark 抓不到包

### ISSUE THREAD

**Issue by Charley-xiao** [ounisangw/CS305-23F-Assignment-1#21]
在 Ubuntu（虚拟机）上打开 Wireshark 选择第一个网卡，运行 `python3 test.py -f 4`，结果抓出来的包中没有一个是 SMTP 或者 POP 的。请问需要对 test.py 做什么修改吗，还是说是 Wireshark 或者虚拟机的问题？谢谢

**Comment by ounisangw** [comment]
虚拟机使用的虚拟网络环境下的数据包传输，自然是无法在本地的wireshark中被捕捉到的。你可以选择依照样例4的流程在本地手动运行一遍并抓包，或是将test.py中各个指令的@timeout注释掉，再在本地运行样例4并抓包。

**Comment by Charley-xiao** [comment]
> 虚拟机使用的虚拟网络环境下的数据包传输，自然是无法在本地的wireshark中被捕捉到的。你可以选择依照样例4的流程在本地手动运行一遍并抓包，或是将test.py中各个指令的@timeout注释掉，再在本地运行样例4并抓包。

好的，谢谢！
