### ISSUE TITLE
编辑agent.py

### ISSUE THREAD

**Issue by WhatWEat** [ounisangw/CS305-23F-Assignment-1#4]
我可以对agent.py进行改动吗？
具体就是在以下代码:
```python
    conn = POP3('localhost', int(fdns_query(POP_SERVER, 'P')))
    print(conn.getwelcome())
    print(conn.user(args.email))
    print(conn.pass_(args.password))
    while True:
        try:
        //自己重写了命令解析
```

**Comment by ounisangw** [comment]
我们提供的agent并不支持list x命令，只支持不带参数的list。你可以在本agent基础上增加功能以支持list x。除此以外，尽可能不要修改agent，否则不保证你的server能够通过最后的测试脚本。当然，在debug阶段用于测试的修改，如输出中间量，是可以的。

**Comment by WhatWEat** [comment]
如果不修改的话，应该无法实现文档中提到的大小写不敏感吧，还是说具体测试的时候是直接给server.py发送指令
> For the commands above, the command names are not case sensitive, but some parameters are case
sensitive for authentication reasons. For example: USER usr1 == user usr1, but USER usr1 != USER
Usr1.

**Comment by ounisangw** [comment]
是的，最终测试的时候会直接与server通信。并且我们的测试要求并不是很高，只要server能正常与agent交互即可通过测试。我们保证不会测试所提供agent中不支持的功能。

**Comment by WhatWEat** [comment]
感觉
