### ISSUE TITLE
server.py SMTP 邮件传输的问题

### ISSUE THREAD

**Issue by WhatWEat** [ounisangw/CS305-23F-Assignment-1#5]
我主要对smtp的邮件传输部分有2个问题：
1.  在这张图中，我注意到发送邮件是在quit之后，但在smtp协议中，邮件的发送难道不是在data结束之后吗？
![](https://github.com/ounisangw/CS305-23F-Assignment-1/blob/main/PA1%20for%20CS305%202023%20Fall_SMTP%20Server/pics/image-20231015230121769.png?raw=true)
2. 我在server.py中接收到data进行transfer的时候，我应该允许使用类似agent.py中的方法，使用来自smtplib的SMTP吧？

**Comment by ounisangw** [comment]
1. 这个与我们的样例实现方式有关。我们的代码只是在quit之后再次打印验证了邮件的发送对象，但实际上还是在data部分进行的邮件传输，因此不需要考虑这里的问题。
2. 由于smtplib库对实现server之间的传输功能这方面的帮助比较大，因此不允许直接调用此库的方法来完成任务。不过，你可以模仿smtplib库函数来实现这部分功能，或者使用这个库来实现调试用的client。
