### ISSUE TITLE
截图提交问题

### ISSUE THREAD

**Issue by vollate** [ounisangw/CS305-23F-Assignment-1#7]
和队友互发邮件，设置了filter后还是有很多包，一张图截不下，需要全部截吗，或者直接提交抓下来的包

**Comment by ounisangw** [comment]
长截图或截图部分的抓包结果均可，只需要在pdf文档中说明你的队友是谁、详细阐述实现过程（截图），并证明你和你的队友可以互相发送并收到消息即可。
